---
title: "Robust testing in meta-analysis by sign-flipping score contributions"
format: pdf
---

## Standard permutation-based methods

Inference using permutations in meta-regression is explained in @Follmann1999-ha and @Higgins2004-gf. In the case of an intercept-only model estimating only the average effect the sign of the observed effect is permuted. When including moderators, the rows of the model matrix are shuffled and then observed effect sizes and variances are re-assigned to each observation. Permutations-based inference has been shown to be robust to model misspecification [ref] but the usual implementation is problematic in two ways. Firstly is extremely computational consuming. After each permutation both fixed effects and random effects are re-computed. A simple meta-analysis models without moderators and $k = 100$ studies takes xxx seconds using the `permutest` function from the `metafor` package. Secondly, in the presence of moderators, shuffling the rows of the model matrix can lead to uncontrolled type-1 error rates under certain conditions.

<!-- more on this and check if true -->

## General approach

Before calculating the effective scores, compared to the standard *flipscores* implementation for Generalized Linear Models, we need to estimate the heterogeneity parameter $\tau^2$ under the constrained model removing the parameter of interest. This require re-fitting the model removing a predictor at time. However, the $\tau^2$ is considered as a nuisance and estimated once under the constrained model. This produce a huge computational advantage where complex models can be fitted faster then using the traditional approach.

## $\tau^2$ estimator

An important choice regards the $\tau^2$ estimator. In `metafor` there are implemented more than ten different estimators. The most common are the restricted maximum likelihood (REML) and the DerSimonian and Laird (DL). The main $\tau^2$ estimators are reviewed in @Viechtbauer2005-zt. So far, we implemented the DL and the REML estimator.

### DL estimator

$$
\hat{\tau}^2_{\mathrm{DL}}
=
\max\left\{
0,\,
\frac{Q-(k-p)}{C}
\right\},
$$

$$
Q
=
(y-X\hat{\beta}_{\mathrm{FE}})^\top
W
(y-X\hat{\beta}_{\mathrm{FE}}),
$$

$$
\hat{\beta}_{\mathrm{FE}}
=
(X^\top W X)^{-1}X^\top W y,
\qquad
W=\operatorname{diag}\left(\frac{1}{v_1},\ldots,\frac{1}{v_k}\right),
$$

$$
C
=
\operatorname{tr}(W)
-
\operatorname{tr}
\left[
(X^\top W X)^{-1}X^\top W^2X
\right].
$$
